##The website title
name: "Sebatyler's Shout"
##Markdown processor
markdown: kramdown
highlighter: rouge

##define base_url for valid usage in sitemap.xml and robots.txt
base_url: http://sebatyler.github.io
sass:
  sass_dir: _sass
  style: :compressed
paginate: 5
paginate_path: "page:num"
##The website description (to be used in meta tags)
description: 맛있는 음식 LA 메탈 여행 스포츠 역사를 좋아하는 8퍼센트 개발자
##Some frequently used keywords on your website
keywords: 방콕, 방콕 마사지, 온눗, 개발, 알바, 모니터링, bangkok, onnut, AWS, rails, ruby, ruby on rails, python, django, 8퍼센트, 8percent, LA 메탈, LA metal, shout, 맛집, 팟타이, 타코, 스포츠, 축구, 역사, 디지털노마드, 재택, 재택근무, 개발자, 프로그래머, 코딩, remote working, programmer, developer, coding, apache, apache module, digital nomad, github, 깃헙, git, github page, github.io, pages.github.com, sebatyler.github.io, sebatyler

##define this for disqus comment support
disqus: sebatyler

##set this to enable google analytics
ga_id: UA-60355624-1
ga_domain: sebatyler.github.io

##Some commonly used links
links:
  facebook: sebatyler
#twitter: username
  email: sebatyler@gmail.com
  github: sebatyler

##put desired image in img/ directory and set the value accordingly. If not defined, a placeholder image will be used.
#about_image: placeholder.jpg
##comment this if you want full width posts with no sidebar
sidebar: on
